# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-17 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
