# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-17 18:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0002_auto_20190117_1825'),
        ('problem', '0002_auto_20190117_1825'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.TextField(db_index=True, default=utils.shortcuts.rand_str, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('username', models.TextField()),
                ('code', models.TextField()),
                ('result', models.IntegerField(db_index=True, default=6)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('language', models.TextField()),
                ('shared', models.BooleanField(default=False)),
                ('statistic_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('ip', models.TextField(null=True)),
                ('repair_info', models.TextField(default='')),
                ('feedback_info', models.TextField(default='')),
                ('wku_info', models.TextField(default='')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
            options={
                'db_table': 'submission',
                'ordering': ('-create_time',),
            },
        ),
    ]
