# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-17 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190117_1825'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acmcontestrank',
            table='acm_contest_rank2',
        ),
        migrations.AlterModelTable(
            name='oicontestrank',
            table='oi_contest_rank2',
        ),
    ]
