# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20190117_1827'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acmcontestrank',
            table='acm_contest_rank',
        ),
        migrations.AlterModelTable(
            name='oicontestrank',
            table='oi_contest_rank',
        ),
    ]
