# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeInfo',
            fields=[
                ('code_id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('pro_id', models.CharField(max_length=20)),
                ('stu_id', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
                ('children_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CodeSrc',
            fields=[
                ('code_id', models.IntegerField(primary_key=True, serialize=False)),
                ('src', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TreeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=20)),
                ('pro_name', models.CharField(default='', max_length=100)),
                ('all_level', models.IntegerField(default=0)),
            ],
        ),
    ]
