# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeinfo',
            name='code_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
