# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 11:44
from __future__ import unicode_literals

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('codeAnalysis', '0003_auto_20181013_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesrc',
            name='src',
            field=utils.models.RichTextField(default=''),
        ),
    ]
